from numpy import *
arr = array([1,2,3,4,5])
print(arr.dtype)
print(arr)
arr = array([1,2,3,4,5.0])
print(arr.dtype)
print(arr)
arr = array([1,2,3,4,5],float)
print(arr.dtype)
print(arr)
arr = array([1.1,2.4,3.5,4.8,5.0],int)
print(arr.dtype)
print(arr)